USE treino-hepta;

CREATE TABLE Montadora (
ID_MONTADORA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(30)
);

CREATE TABLE Carro (
ID_CARRO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
MODELO VARCHAR(50),
FK_MONTADORA INT,
COR VARCHAR(20),
DATAENTRADA DATE,
FOREIGN KEY (FK_MONTADORA) 
REFERENCES Montadora(ID_MONTADORA)
ON DELETE CASCADE
);

CREATE TABLE Foto (
ID_FOTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
PATH VARCHAR(256),
FK_CARRO INT,
FOREIGN KEY (FK_CARRO) 
REFERENCES Carro(ID_CARRO)
ON DELETE CASCADE
);
